#!/bin/bash

# Проверка наличия аргумента с именем пользователя
if [ $# -eq 0 ]; then
    echo "Usage: $0 <client_name>"
    exit 1
fi

# Имя пользователя, переданное в качестве аргумента
CLIENT_NAME=$1

# Установка переменной окружения EASYRSA в текущую директорию EasyRSA
export EASYRSA=/etc/openvpn/easy-rsa

# Переход в директорию EasyRSA
cd $EASYRSA

# Генерация клиентского ключа и запроса сертификата с указанным именем
echo -e "Name_$CLIENT_NAME\n\n\n\n\n\n\n\n\n\n" | sudo ./easyrsa gen-req $CLIENT_NAME nopass

# Подписание запроса клиентского сертификата с ключом CA
echo -e "yes" | sudo ./easyrsa sign-req client $CLIENT_NAME

# Создание файла конфигурации для клиента
CLIENT_CONFIG=/etc/openvpn/openvpn-client-config-$CLIENT_NAME.ovpn
cp /etc/openvpn/openvpn-client-config.ovpn $CLIENT_CONFIG

# Замена IP-адреса в файле конфигурации OpenVPN на фактический IPv4-адрес сервера
server_ip=$(curl -4 ifconfig.co)  # Получение IPv4-адреса сервера с использованием curl
sed -i "s/remote 123.123.123.123/remote $server_ip/g" $CLIENT_CONFIG

# Вставка содержимого файла ca.crt
echo "<ca>" >> $CLIENT_CONFIG
cat /etc/openvpn/certs/ca.crt >> $CLIENT_CONFIG
echo "</ca>" >> $CLIENT_CONFIG

# Вставка содержимого файла client.crt
echo "<cert>" >> $CLIENT_CONFIG
cat /etc/openvpn/easy-rsa/pki/issued/$CLIENT_NAME.crt >> $CLIENT_CONFIG
echo "</cert>" >> $CLIENT_CONFIG

# Вставка содержимого файла client.key
echo "<key>" >> $CLIENT_CONFIG
cat /etc/openvpn/easy-rsa/pki/private/$CLIENT_NAME.key >> $CLIENT_CONFIG
echo "</key>" >> $CLIENT_CONFIG

# Вставка содержимого файла ta.key
echo "<tls-auth>" >> $CLIENT_CONFIG
cat /etc/openvpn/certs/ta.key >> $CLIENT_CONFIG
echo "</tls-auth>" >> $CLIENT_CONFIG

# Перемещение файла конфигурации клиента OpenVPN в директорию Apache
sudo mv $CLIENT_CONFIG /var/www/html/

# Изменение прав доступа к файлу конфигурации на только чтение
sudo chmod 444 /var/www/html/openvpn-client-config-$CLIENT_NAME.ovpn

# Отображение URL для пользователя
echo -e "Your file is available at the following \e[32mURL: http://$server_ip/openvpn-client-config-$CLIENT_NAME.ovpn\e[0m"
