#!/bin/bash

# Проверка наличия аргумента с именем пользователя
if [ $# -eq 0 ]; then
    echo "Usage: $0 <client_name>"
    exit 1
fi

# Имя пользователя, переданное в качестве аргумента
CLIENT_NAME=$1

# Установка переменной окружения EASYRSA в текущую директорию EasyRSA
export EASYRSA=/etc/openvpn/easy-rsa

# Переход в директорию EasyRSA
cd $EASYRSA

# Генерация клиентского ключа и запроса сертификата с указанным именем
echo -e "Name_$CLIENT_NAME\n\n\n\n\n\n\n\n\n\n" | sudo ./easyrsa gen-req $CLIENT_NAME nopass

# Подписание запроса клиентского сертификата с ключом CA
echo -e "yes" | sudo ./easyrsa sign-req client $CLIENT_NAME

# Создание файла конфигурации для клиента
CLIENT_CONFIG=/etc/openvpn/openvpn-client-config-$CLIENT_NAME.ovpn

# Создание файла конфигурации на основе стандартного шаблона
cat <<EOF > $CLIENT_CONFIG
client
dev tun
proto udp
remote $(curl -4 ifconfig.co) 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
auth SHA256
compress lz4-v2
verb 3
<ca>
$(cat /etc/openvpn/certs/ca.crt)
</ca>
<cert>
$(cat /etc/openvpn/easy-rsa/pki/issued/$CLIENT_NAME.crt)
</cert>
<key>
$(cat /etc/openvpn/easy-rsa/pki/private/$CLIENT_NAME.key)
</key>
<tls-auth>
$(cat /etc/openvpn/certs/ta.key)
</tls-auth>
key-direction 1
EOF

# Перемещение файла конфигурации клиента OpenVPN в директорию Apache
sudo mv $CLIENT_CONFIG /var/www/html/

# Изменение прав доступа к файлу конфигурации на только чтение
sudo chmod 444 /var/www/html/openvpn-client-config-$CLIENT_NAME.ovpn

# Отображение URL для пользователя
echo -e "Your file is available at the following \e[32mURL: http://$(curl -4 ifconfig.co)/openvpn-client-config-$CLIENT_NAME.ovpn\e[0m"
