#!/bin/bash

# Проверка наличия аргумента с именем пользователя
if [ $# -eq 0 ]; then
    echo "Usage: $0 <client_name>"
    exit 1
fi

CLIENT_NAME=$1

# Переменная окружения EASYRSA
export EASYRSA=/etc/openvpn/easy-rsa
cd $EASYRSA

# Генерация запроса на сертификат и ключ клиента
echo -e "Name_$CLIENT_NAME\n\n\n\n\n\n\n\n\n\n" | sudo ./easyrsa gen-req $CLIENT_NAME nopass
echo -e "yes" | sudo ./easyrsa sign-req client $CLIENT_NAME

# Создание конфигурационного файла клиента
CLIENT_CONFIG="/etc/openvpn/openvpn-client-config-$CLIENT_NAME.ovpn"
server_ip=$(curl -4 ifconfig.co)
cat <<EOF > $CLIENT_CONFIG
client
dev tun
proto udp
remote $server_ip 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
auth SHA256
compress lz4-v2
verb 3
<ca>
$(cat /etc/openvpn/certs/ca.crt)
</ca>
<cert>
$(cat /etc/openvpn/easy-rsa/pki/issued/$CLIENT_NAME.crt)
</cert>
<key>
$(cat /etc/openvpn/easy-rsa/pki/private/$CLIENT_NAME.key)
</key>
<tls-auth>
$(cat /etc/openvpn/certs/ta.key)
</tls-auth>
key-direction 1
EOF

# Перемещение конфигурации клиента в директорию Apache
sudo mv $CLIENT_CONFIG /var/www/html/
sudo chmod 444 /var/www/html/$CLIENT_CONFIG

# Вывод URL для загрузки файла клиента
echo -e "Ваш файл доступен по следующему URL: \e[32mhttp://$server_ip/$CLIENT_CONFIG\e[0m"
