#!/bin/bash

# Обновление списка пакетов
sudo apt update

# Установка необходимых пакетов
sudo apt install -y openvpn easy-rsa net-tools curl apache2

# Копирование EasyRSA в /etc/openvpn
sudo cp -R /usr/share/easy-rsa /etc/openvpn/
cd /etc/openvpn/easy-rsa

# Установка переменной окружения EASYRSA
export EASYRSA=$(pwd)

# Инициализация PKI
sudo ./easyrsa init-pki

# Создание CA без пароля
sudo EASYRSA_BATCH=1 ./easyrsa build-ca nopass

# Создание директорий для сертификатов и ключей
mkdir -p /etc/openvpn/certs/

# Копирование CA сертификата
cp pki/ca.crt /etc/openvpn/certs/

# Генерация запроса на сертификат и ключ сервера
sudo ./easyrsa gen-req server nopass
sudo ./easyrsa sign-req server server

# Генерация запроса на сертификат и ключ клиента
CLIENT_NAME="client1"
sudo ./easyrsa gen-req $CLIENT_NAME nopass
sudo ./easyrsa sign-req client $CLIENT_NAME

# Копирование сертификатов и ключей
sudo cp pki/issued/server.crt /etc/openvpn/certs/
sudo cp pki/private/server.key /etc/openvpn/certs/
sudo cp pki/issued/$CLIENT_NAME.crt /etc/openvpn/certs/
sudo cp pki/private/$CLIENT_NAME.key /etc/openvpn/certs/

# Генерация параметров Диффи-Хеллмана
openssl dhparam -out /etc/openvpn/certs/dh2048.pem 2048

# Генерация HMAC ключа
openvpn --genkey --secret /etc/openvpn/certs/ta.key

# Проверка наличия файлов
REQUIRED_FILES=(
    "/etc/openvpn/certs/ca.crt"
    "/etc/openvpn/certs/server.crt"
    "/etc/openvpn/certs/server.key"
    "/etc/openvpn/certs/dh2048.pem"
    "/etc/openvpn/certs/ta.key"
    "/etc/openvpn/certs/$CLIENT_NAME.crt"
    "/etc/openvpn/certs/$CLIENT_NAME.key"
)

MISSING_FILES=()
for file in "${REQUIRED_FILES[@]}"; do
    if [ ! -f "$file" ]; then
        MISSING_FILES+=("$file")
    fi
done

if [ ${#MISSING_FILES[@]} -eq 0 ]; then
    echo "Все необходимые файлы присутствуют в /etc/openvpn/certs/"
else
    echo "Ошибка: Не все необходимые файлы присутствуют в /etc/openvpn/certs/"
    echo "Отсутствующие файлы:"
    for file in "${MISSING_FILES[@]}"; do
        echo "  $file"
    done
    exit 1
fi

# Загрузка конфигурации сервера
cd /etc/openvpn
wget -O server.conf https://raw.githubusercontent.com/Dpwerfew/openVPN/main/server.conf

# Запуск и включение OpenVPN
sudo systemctl start openvpn@server.service
sudo systemctl enable openvpn@server.service

# Настройка маршрутизации
cd /root/bin
wget -O vpn_route.sh https://raw.githubusercontent.com/Dpwerfew/openVPN/main/vpn_route.sh
sed -i "s/DEV='[^']*'/DEV='$(route | grep '^default' | grep -o '[^ ]*$')'/g" vpn_route.sh
chmod 755 vpn_route.sh
bash vpn_route.sh

# Настройка службы маршрутизации
cd /etc/systemd/system
wget -O openvpn-server-routing.service https://raw.githubusercontent.com/Dpwerfew/openVPN/main/openvpn-server-routing.service
systemctl enable openvpn-server-routing

# Создание конфигурационного файла клиента
cd /etc/openvpn
CLIENT_CONFIG="openvpn-client-config-$CLIENT_NAME.ovpn"
server_ip=$(curl -4 ifconfig.co)
cat <<EOF > $CLIENT_CONFIG
client
dev tun
proto udp
remote $server_ip 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
auth SHA256
compress lz4-v2
verb 3
<ca>
$(cat /etc/openvpn/certs/ca.crt)
</ca>
<cert>
$(cat /etc/openvpn/certs/$CLIENT_NAME.crt)
</cert>
<key>
$(cat /etc/openvpn/certs/$CLIENT_NAME.key)
</key>
<tls-auth>
$(cat /etc/openvpn/certs/ta.key)
</tls-auth>
key-direction 1
EOF

# Перемещение конфигурации клиента в директорию Apache
sudo mv $CLIENT_CONFIG /var/www/html/
sudo chmod 444 /var/www/html/$CLIENT_CONFIG

# Вывод URL для загрузки файла клиента
echo -e "Ваш файл доступен по следующему URL: \e[32mhttp://$server_ip/$CLIENT_CONFIG\e[0m"
